# -*- coding: utf-8 -*-
"""Streamlit_ejemplo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fG_bjXdkvo62nFRoe-0myMDhFuqXmFlg
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')